name: "rescue.zero-totp.com deployment"

on:
  push:
   # tags:
   #   - '**'

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    name: Build frontend
    steps:
      - uses: actions/checkout@v3
      - name: Create environment file
        working-directory: ./frontend
        run: bash generate-env.sh '${{ github.ref_name }}' '${{secrets.RSA_PUBLIC_KEY}}'
      - name : Install dependencies 
        working-directory: ./frontend
        run: npm ci
      - name : Build app
        working-directory: ./frontend
        run: ng build --configuration production --subresource-integrity
        
        
