name: "rescue.zero-totp.com deployment"

on:
  push:
   # tags:
   #   - '**'
   
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    name: Build frontend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Create environment file
        working-directory: ./frontend
        run: bash generate-env.sh '${{ github.ref_name }}' '${{secrets.RSA_PUBLIC_KEY}}'
      - name : Install dependencies 
        working-directory: ./frontend
        run: npm ci
      - name: Install angular CLI
        run : npm install -g @angular/cli
      - name : Build app
        working-directory: ./frontend
        run:  ng build --configuration production --subresource-integrity
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist  
        
  deploy:
    needs: frontend-build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
